/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tempconvert;

import javax.swing.JOptionPane;
import java.awt.event.*;
import tempconver.*;
/**
 *
 * @author geoffreytrenard
 */
public class TempConvertApp extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form TempConvertApp
     */
    public TempConvertApp() {
        initComponents();
        fahrToCel.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dgrsInput = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        fahrToCel = new javax.swing.JButton();
        celToFahr = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        dgrsOutput = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please enter the degrees you want converted.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 26));

        dgrsInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dgrsInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dgrsInputActionPerformed(evt);
            }
        });
        jPanel1.add(dgrsInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 290, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        fahrToCel.setText("Fahrenheit to Celsius");
        fahrToCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fahrToCelActionPerformed(evt);
            }
        });
        jPanel2.add(fahrToCel);

        celToFahr.setText("Celsius to Fahrenheit");
        jPanel2.add(celToFahr);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.add(dgrsOutput);

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel3.add(resetBtn);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dgrsInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dgrsInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dgrsInputActionPerformed
    @Override
    private void fahrToCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fahrToCelActionPerformed
                try{
                    double degrees = Double.parseDouble(dgrsInput.getDegrees());
                    TempConvert tempconvert = new TempConvert(degrees);
                    results = new StringBuffer(dgrsOutput.ferConvert());
                    
                }catch (Exception e){//Catch a number format exception.
           JOptionPane.showMessageDialog(this, "An error occured");
                }
                        
    }//GEN-LAST:event_fahrToCelActionPerformed
    // Clear the Form
    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        dgrsInput.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempConvertApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempConvertApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempConvertApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempConvertApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempConvertApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton celToFahr;
    private javax.swing.JTextField dgrsInput;
    private javax.swing.JLabel dgrsOutput;
    private javax.swing.JButton fahrToCel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
